## CONTRACT DETAILS - UFA AND RFA
### UFAs 2024:

In [22]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# This is a hypothetical URL extracted from the iframe src attribute
url = 'https://puckpedia.com/e/players?q=3CKXYY&sz=750'

# Send an HTTP request and get the response
response = requests.get(url)

# Parse the response content with BeautifulSoup
soup = BeautifulSoup(response.content, 'html.parser')

# Find the table in the parsed HTML
table = soup.find('table')  # You might need to refine this to find the exact table

# Convert the table to a pandas DataFrame
df_UFA_2024 = pd.read_html(str(table), index_col=0)[0]
df_UFA_2024

,Playeraverages,Team,Current Cap Hit,Current Salary,Contract Length,Current Cap %,Age,Height,Weight,Pos,...,2023-24 GAA,2023-24 SV%,2022-23 GF%,2022-23 DFF%,2022-23 relDFF%,2022-23 CF%,2022-23 relCF%,2022-23 G60,2022-23 P60,2022-23 GSAx
1,"Stamkos, Steven",NaN,"$8,500,000","$6,500,000",8,10.2%,34,73in,194lbs,C,...,NaN,NaN,54.90,50.60,-2.40,49.60,-2.8,0.86,2.20,NaN
2,"Voracek, Jakub",NaN,"$8,250,000","$7,500,000",8,9.9%,34,74in,209lbs,RW,...,NaN,NaN,33.29,35.70,-14.50,38.40,-9.5,NaN,1.79,NaN
3,"Seabrook, Brent",NaN,"$6,875,000","$4,500,000",8,8.2%,38,75in,220lbs,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Reinhart, Sam",NaN,"$6,500,000","$6,500,000",3,7.8%,28,74in,194lbs,C,...,NaN,NaN,46.40,55.40,2.29,55.29,1.2,0.50,1.61,NaN
5,"Murray, Matt",NaN,"$6,250,000","$8,000,000",4,7.5%,29,76in,179lbs,G,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
374,"Gust, Dave",NaN,"$762,500","$775,000",2,0.9%,30,70in,176lbs,RW,...,NaN,NaN,40.00,51.80,9.60,51.50,11.3,1.18,1.18,NaN
375,"Heatherington, Dillon",NaN,"$762,500","$775,000",2,0.9%,28,76in,216lbs,D,...,NaN,NaN,NaN,49.40,-0.40,47.90,0.1,NaN,NaN,NaN
376,"Gawdin, Glenn",NaN,"$762,500","$775,000",2,0.9%,27,73in,192lbs,C,...,NaN,NaN,NaN,50.79,7.30,45.50,-1.2,NaN,NaN,NaN
377,"Rempal, Sheldon",NaN,"$762,500","$775,000",2,0.9%,28,70in,165lbs,RW,...,NaN,NaN,NaN,1.80,-54.30,35.70,-20.3,NaN,NaN,NaN
378,"Barre-Boulet, Alex",NaN,"$758,333","$775,000",3,0.9%,26,70in,181lbs,C,...,NaN,NaN,NaN,82.90,15.90,50.00,-3.4,NaN,NaN,NaN

In [25]:
#Dropping Goalies:
df_UFA_2024 = df_UFA_2024.drop(df_UFA_2024[df_UFA_2024.Pos == 'G'].index) #Removed Goalies sincenot considering them

#Changing the Column with the Player Name to be more appropriately named
df_UFA_2024.rename(columns={'Playeraverages': 'Player'}, inplace=True)
# Ensure that 'Player' column is of string type and not float or NaN
df_UFA_2024['Player'] = df_UFA_2024['Player'].astype(str)
# Split the string on comma, reverse, and join with a space
df_UFA_2024['Player'] = df_UFA_2024['Player'].apply(lambda x: ' '.join(x.split(',')[::-1]).strip())
df_UFA_2024['Player'] = df_UFA_2024['Player'].astype(str) # convert it back to a string

In [26]:
# Drop Columns that have all NaNs or very few bits of data or game-related info since I have the players' statistics:
UFA_drop_cols = ['Team', 'Clause', 'Age', 'Height', 'Weight',  'Shoots','Pos','2023-24 GP', '2023-24 G', '2023-24 A',
                 '2023-24 P', '2023-24 PPG','2023-24 GPG', '2023-24 5x5 TOI', '2023-24 5x5 TOI/G',
                 '2023-24 GAA', '2023-24 SV%','2022-23 GF%', '2022-23 DFF%', '2022-23 relDFF%',
                 '2022-23 CF%', '2022-23 relCF%', '2022-23 G60', '2022-23 P60', '2022-23 GSAx', 'Signing Status', 'Start Yr']

In [27]:
df_UFA_2024_dropped = df_UFA_2024.drop(columns=UFA_drop_cols)

In [30]:
df_UFA_2024_dropped.info()

<class 'pandas.core.frame.DataFrame'>
Index: 330 entries, 1 to 378
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Player            330 non-null    object
 1   Current  Cap Hit  330 non-null    object
 2   Current  Salary   330 non-null    object
 3   Contract  Length  330 non-null    int64
 4   Current  Cap %    330 non-null    object
 5   UFA Year          330 non-null    int64
 6   Contract Type     330 non-null    object
 7   Expiry Status     330 non-null    object
 8   Expiry Yr         330 non-null    object
 9   Agent             330 non-null    object
dtypes: int64(2), object(8)
memory usage: 28.4+ KB

In [29]:
df_UFA_2024_dropped.loc[df_UFA_2024_dropped['Agent'].isna(), 'Agent'] = 'No Agent'

In [31]:
df_UFA_2024 = df_UFA_2024_dropped.copy()

### RFAs 2024:

In [32]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

# Replace with the actual URL you get from the iframe
url = 'https://puckpedia.com/e/players?q=33VEJC&sz=750'

# This will get the content from the URL, assuming it's not loaded dynamically
response = requests.get(url)
soup = BeautifulSoup(response.content, 'html.parser')

# Assuming the table is properly formatted and identifiable
table = soup.find('table')

# Now we convert it into a DataFrame
# index_col=0 will use the first column as the index
df_RFA_2024 = pd.read_html(str(table), index_col=0)[0]

In [33]:
#Dropping Goalies:
df_RFA_2024 = df_RFA_2024.drop(df_RFA_2024[df_RFA_2024.Pos == 'G'].index) #Removed Goalies sincenot considering them

#Changing the Column with the Player Name to be more appropriately named
df_RFA_2024.rename(columns={'Playeraverages': 'Player'}, inplace=True)
# Ensure that 'Player' column is of string type and not float or NaN
df_RFA_2024['Player'] = df_RFA_2024['Player'].astype(str)
# Split the string on comma, reverse, and join with a space
df_RFA_2024['Player'] = df_RFA_2024['Player'].apply(lambda x: ' '.join(x.split(',')[::-1]).strip())
df_RFA_2024['Player'] = df_RFA_2024['Player'].astype(str) # convert it back to a string

In [42]:
df_RFA_2024.loc[df_RFA_2024['Agent'].isna(), 'Agent'] = 'No Agent'

In [46]:
df_RFA_2024_dropped.info()

<class 'pandas.core.frame.DataFrame'>
Index: 291 entries, 1 to 324
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Player            291 non-null    object
 1   Current  Cap Hit  291 non-null    object
 2   Current  Salary   291 non-null    object
 3   Contract  Length  291 non-null    int64
 4   Current  Cap %    291 non-null    object
 5   UFA Year          291 non-null    int64
 6   Contract Type     291 non-null    object
 7   Expiry Status     291 non-null    object
 8   Expiry Yr         291 non-null    object
 9   Agent             291 non-null    object
dtypes: int64(2), object(8)
memory usage: 25.0+ KB

In [44]:
# Drop Columns that have all NaNs or very few bits of data or game-related info since I have the players' statistics:
RFA_drop_cols = ['Team', 'Age', 'Height',  'Weight', 'Pos','Clause', '2023-24 GP', '2023-24 G', '2023-24 A',
                 '2023-24 P', '2023-24 PPG','2023-24 GPG', '2023-24 5x5 TOI', '2023-24 5x5 TOI/G',
                 '2023-24 GAA', '2023-24 SV%','2022-23 GF%', '2022-23 DFF%', '2022-23 relDFF%',
                 '2022-23 CF%', '2022-23 relCF%', '2022-23 G60', '2022-23 P60', '2022-23 GSAx', 'Shoots', 'Signing Status', 'Start Yr']

In [45]:
df_RFA_2024_dropped = df_RFA_2024.drop(columns=RFA_drop_cols)

In [37]:
df_RFA_2024 = df_RFA_2024_dropped.copy()

In [47]:
set(df_RFA_2024_dropped.columns).intersection(set(df_UFA_2024_dropped.columns))

{'Agent',
 'Contract  Length',
 'Contract Type',
 'Current  Cap %',
 'Current  Cap Hit',
 'Current  Salary',
 'Expiry Status',
 'Expiry Yr',
 'Player',
 'UFA Year'}

In [53]:
frames = [df_UFA_2024_dropped, df_RFA_2024_dropped]

df_2024_NHL_expr_contract_details = pd.concat(frames, axis=0, join= 'outer',ignore_index=False)

df_2024_NHL_expr_contract_details.shape

(621, 10)

In [61]:
df_2024_NHL_expr_contract_details  = df_2024_NHL_expr_contract_details.reset_index(drop=True)
df_2024_NHL_expr_contract_details

,Player,Current Cap Hit,Current Salary,Contract Length,Current Cap %,UFA Year,Contract Type,Expiry Status,Expiry Yr,Agent
0,Steven Stamkos,"$8,500,000","$6,500,000",8,10.2%,2016,Standard,UFA,2023-24,Donald Meehan
1,Jakub Voracek,"$8,250,000","$7,500,000",8,9.9%,2015,Standard,UFA,2023-24,No Agent
2,Brent Seabrook,"$6,875,000","$4,500,000",8,8.2%,2012,Standard,UFA,2023-24,Gerry Johannson
3,Sam Reinhart,"$6,500,000","$6,500,000",3,7.8%,2022,Standard,UFA,2023-24,Craig Oster
4,Jake Guentzel,"$6,000,000","$6,000,000",5,7.2%,2022,Standard,UFA,2023-24,Ben Hankinson
...,...,...,...,...,...,...,...,...,...,...
616,Tyce Thompson,"$762,500","$775,000",2,0.9%,2027,Standard,RFA +arb,2023-24,Jerry Buckley
617,Arnaud Durandeau,"$762,500","$775,000",2,0.9%,2026,Standard,UFA-Group6,2023-24,Paul Corbeil
618,Dennis Cholowski,"$762,500","$775,000",2,0.9%,2025,Standard,RFA +arb,2023-24,Allain Roy
619,Taylor Raddysh,"$758,333","$775,000",3,0.9%,2025,Standard,RFA +arb,2023-24,David Gagner
620,Boris Katchouk,"$758,333","$775,000",3,0.9%,2025,Standard,RFA +arb,2023-24,Robert Hooper

In [62]:
df_2024_NHL_expr_contract_details.to_csv('NHL_expr_contract_details_2024.csv', index=False)

## Bring in the All_strengths CSV so that I can use the team column from that one and create a team column in this one

In [65]:
df_all_stats_AS_clean = pd.read_csv('NHL_Skater_AS_All_Stats_Clean.csv')

In [68]:
# Make a df with just the 2024 stats so I can link the team to the contract table:
df_AS_2024 = df_all_stats_AS_clean.loc[df_all_stats_AS_clean['Season'] == 2024]
df_AS_2024

,Player,Team,Position,Age,GP,TOI,Goals,Total Assists,First Assists,Second Assists,...,LDGA/60,Off. Zone Starts/60,Neu. Zone Starts/60,Def. Zone Starts/60,On The Fly Starts/60,Off. Zone Faceoffs/60,Neu. Zone Faceoffs/60,Def. Zone Faceoffs/60,Season,Age_Group
1952,Ryan Suter,DAL,D,39,75,1430.633333,2,15,7,8,...,0.42,6.79,11.58,8.81,45.46,17.66,17.66,21.10,2024,Old Vet
1953,Jeff Carter,PIT,C,39,65,809.000000,9,4,2,2,...,0.75,5.12,10.75,20.69,52.14,9.12,15.13,33.23,2024,Old Vet
1954,Zach Parise,COL,L,40,23,304.316667,4,5,2,3,...,1.14,8.48,11.83,11.63,54.81,14.59,16.56,22.48,2024,Old Vet
1955,Brent Burns,CAR,D,39,75,1628.000000,10,29,11,18,...,0.59,10.47,10.58,8.77,39.84,25.36,17.17,19.94,2024,Old Vet
1956,Corey Perry,EDM,R,39,45,600.866667,10,8,5,3,...,0.58,12.68,10.48,7.09,41.64,24.07,15.58,14.88,2024,Old Vet

In [73]:
df_merged = pd.merge(df_2024_NHL_expr_contract_details,
                     df_AS_2024[['Player', 'Team']],
                     on='Player', how='left')

df_merged.loc[df_merged['Team'].isna()]

,Player,Current Cap Hit,Current Salary,Contract Length,Current Cap %,UFA Year,Contract Type,Expiry Status,Expiry Yr,Agent,Team
1,Jakub Voracek,"$8,250,000","$7,500,000",8,9.9%,2015,Standard,UFA,2023-24,No Agent,NaN
2,Brent Seabrook,"$6,875,000","$4,500,000",8,8.2%,2012,Standard,UFA,2023-24,Gerry Johannson,NaN
8,Jake Muzzin,"$5,625,000","$4,000,000",4,6.7%,2016,Standard,UFA,2023-24,Joseph Resnick,NaN
12,Bryan Little,"$5,291,666","$3,750,000",6,6.3%,2014,Standard,UFA,2023-24,Paul Capizzano,NaN
17,Josh Bailey,"$5,000,000","$3,500,000",6,6%,2016,Standard,UFA,2023-24,Patrick Morris,NaN
...,...,...,...,...,...,...,...,...,...,...,...
614,William Bitten,"$762,500","$775,000",2,0.9%,2026,Standard,UFA-Group6,2023-24,Serge Payer,NaN
615,Kyle Capobianco,"$762,500","$775,000",2,0.9%,2025,Standard,UFA-Group6,2023-24,Paul Capizzano,NaN
617,Tyce Thompson,"$762,500","$775,000",2,0.9%,2027,Standard,RFA +arb,2023-24,Jerry Buckley,NaN
618,Arnaud Durandeau,"$762,500","$775,000",2,0.9%,2026,Standard,UFA-Group6,2023-24,Paul Corbeil,NaN
619,Dennis Cholowski,"$762,500","$775,000",2,0.9%,2025,Standard,RFA +arb,2023-24,Allain Roy,NaN

In [80]:
df_merged_alt = pd.merge(df_AS_2024[['Player', 'Team']],
                         df_2024_NHL_expr_contract_details,
                         on='Player', how='left')

df_merged_alt_missing = df_merged_alt.loc[df_merged_alt['Current  Cap Hit'].isna()]

df_exp_contracts_2024 = df_merged_alt.drop(df_merged_alt_missing.index)
df_exp_contracts_2024.reset_index(drop=True)

,Player,Team,Current Cap Hit,Current Salary,Contract Length,Current Cap %,UFA Year,Contract Type,Expiry Status,Expiry Yr,Agent
0,Jeff Carter,PIT,"$3,125,000","$3,000,000",2.0,3.7%,2012.0,Standard,UFA,2023-24,Richard Curran
1,Zach Parise,COL,"$825,000","$825,000",1.0,1%,2012.0,Standard,UFA,2023-24,Wade Arnott
2,Corey Perry,EDM,"$775,000","$775,000",1.0,0.9%,2012.0,Standard,UFA,2023-24,Patrick Morris
3,Joe Pavelski,DAL,"$3,500,000","$3,500,000",1.0,4.2%,2012.0,Standard,UFA,2023-24,Daniel Plante
4,Mark Giordano,TOR,"$800,000","$800,000",2.0,1%,2011.0,Standard,UFA,2023-24,Ritchie Winter
...,...,...,...,...,...,...,...,...,...,...,...
351,Cole McWard,VAN,"$922,500","$895,000",2.0,1.1%,2028.0,Entry Level,RFA,2023-24,Allain Roy
352,Jiri Smejkal,OTT,"$870,000","$870,000",1.0,1%,2024.0,Entry Level,UFA,2023-24,Craig Oster
353,Nikolas Matinpalo,OTT,"$885,000","$885,000",1.0,1.1%,2026.0,Entry Level,RFA +arb,2023-24,Murray Koontz
354,Waltteri Merela,T.B,"$870,000","$870,000",1.0,1%,2026.0,Entry Level,RFA +arb,2023-24,Mark Gandler & Todd Diamond
355,Patrik Koch,ARI,"$847,500","$847,500",1.0,1%,2024.0,Entry Level,UFA,2023-24,Serge Payer

In [82]:
df_exp_contracts_2024.to_csv('NHL_expr_contract_details_2024.csv', index=False)